/**
 * lib/email-templates/weekly-digest.ts
 *
 * Weekly digest email sent by /api/cron/weekly for every active/trialing
 * customer. Includes AVS score, week-over-week delta, top-3 gap prompts,
 * and a CTA link to the full dashboard report.
 *
 * Uses the shared NeuralReach email layout (lib/email-templates/layout.ts)
 * for the outer wrapper (wordmark header + footer). The inner data tables
 * (score hero, per-LLM bars, gap rows, pro upsell) stay template-specific
 * because they're product UI, not chrome.
 */

import { wrapEmail, button, COLORS } from "./layout";

export interface GapPrompt {
  prompt_id?: string;
  prompt_text: string;
  category: string;
  llms_missed: string[];
}

export interface WeeklyDigestParams {
  appUrl: string;
  brandName: string;
  avsBrand: number;
  prevAvsBrand: number | null;
  perLlm: Record<string, number>;
  gapPrompts: GapPrompt[];
  plan: "starter" | "pro";
  runDate: string;
}

const LLM_LABELS: Record<string, string> = {
  openai: "ChatGPT",
  anthropic: "Claude",
  perplexity: "Perplexity",
  google: "Google AIO",
};

function formatDelta(delta: number): string {
  if (delta > 0) return `+${delta.toFixed(1)}`;
  if (delta < 0) return `${delta.toFixed(1)}`;
  return "+/-0.0";
}

function deltaColor(delta: number): string {
  if (delta > 0) return "#16a34a";
  if (delta < 0) return "#dc2626";
  return COLORS.muted;
}

function scoreColor(score: number): string {
  if (score >= 70) return "#16a34a";
  if (score >= 40) return "#d97706";
  return "#dc2626";
}

function barWidth(score: number): number {
  return Math.max(4, Math.min(100, score));
}

export function weeklyDigestEmail(params: WeeklyDigestParams): {
  subject: string;
  html: string;
  text: string;
} {
  const {
    appUrl,
    brandName,
    avsBrand,
    prevAvsBrand,
    perLlm,
    gapPrompts,
    plan,
    runDate,
  } = params;

  const delta = prevAvsBrand !== null ? avsBrand - prevAvsBrand : null;
  const dashboardUrl = `${appUrl}/dashboard`;
  const supportEmail = "support@neuralreach.de";

  const runDateDisplay = new Date(runDate + "T12:00:00Z").toLocaleDateString(
    "en-US",
    { weekday: "long", year: "numeric", month: "long", day: "numeric" }
  );

  const subject = `${brandName} AI visibility ${avsBrand.toFixed(1)}/100${
    delta !== null
      ? ` (${delta >= 0 ? "+" : ""}${delta.toFixed(1)} vs last week)`
      : ""
  }`;

  // ── Per-LLM rows ───────────────────────────────────────────────────────
  const llmRowsHtml = Object.entries(perLlm)
    .map(([key, score]) => {
      const label = LLM_LABELS[key] ?? key;
      const color = scoreColor(score);
      const width = barWidth(score);
      return `
<tr>
<td style="padding:6px 0;font-size:14px;color:${COLORS.ink};width:120px;">${label}</td>
<td style="padding:6px 0;">
<table cellpadding="0" cellspacing="0" border="0" width="100%"><tr>
<td style="background:${COLORS.hairline};border-radius:4px;height:8px;">
<div style="background:${color};width:${width}%;height:8px;border-radius:4px;"></div>
</td></tr></table>
</td>
<td style="padding:6px 0 6px 12px;font-size:14px;font-weight:600;color:${color};white-space:nowrap;width:60px;">${score.toFixed(1)}/100</td>
</tr>`;
    })
    .join("");

  // ── Gap prompt rows ────────────────────────────────────────────────────
  const gapRowsHtml =
    gapPrompts.length > 0
      ? gapPrompts
          .map(
            (g, i) => `
<tr><td style="padding:10px 0;border-bottom:1px solid ${COLORS.hairline};">
<div style="font-size:14px;font-weight:600;color:${COLORS.ink};margin-bottom:4px;">${i + 1}. &ldquo;${g.prompt_text}&rdquo;</div>
<div style="font-size:13px;color:${COLORS.muted};">
Missed by: ${g.llms_missed.map((k) => LLM_LABELS[k] ?? k).join(", ") || "all LLMs"} &nbsp;&middot;&nbsp; Category: ${g.category}
</div>
</td></tr>`
          )
          .join("")
      : `<tr><td style="padding:10px 0;font-size:14px;color:#16a34a;">No significant gaps this week.</td></tr>`;

  // ── Pro upsell (Starter only) ──────────────────────────────────────────
  const proBlurbHtml =
    plan === "starter"
      ? `<table cellpadding="0" cellspacing="0" border="0" width="100%" style="background:#eff6ff;border-radius:8px;border:1px solid #bfdbfe;margin:20px 0;"><tr><td style="padding:16px 18px;">
<p style="margin:0 0 6px;font-size:14px;font-weight:600;color:#1d4ed8;">Upgrade to Pro for a full Fix Report</p>
<p style="margin:0 0 10px;font-size:13px;color:${COLORS.ink};line-height:1.5;">Pro subscribers get a personalised markdown Fix Report with schema markup, content gaps, and entity authority recommendations, generated by Claude for each weekly run.</p>
<a href="${appUrl}/pricing" style="font-size:13px;color:${COLORS.brandBlue};font-weight:600;text-decoration:underline;">Upgrade to Pro</a>
</td></tr></table>`
      : "";

  // ── Body fragment (wrapEmail() supplies the wordmark header + footer) ──
  const bodyHtml = `
<p style="margin:0 0 4px;font-size:13px;color:${COLORS.muted};">${runDateDisplay}</p>
<h1 style="margin:0 0 20px;font-size:24px;font-weight:700;color:${COLORS.ink};line-height:1.2;">AI visibility report for ${brandName}</h1>

<table cellpadding="0" cellspacing="0" border="0" style="margin:0 0 24px 0;"><tr>
<td style="padding-right:24px;vertical-align:top;">
<div style="font-size:48px;font-weight:800;color:${scoreColor(avsBrand)};line-height:1;">${avsBrand.toFixed(1)}</div>
<div style="font-size:13px;color:${COLORS.muted};margin-top:2px;">out of 100</div>
</td>
${
  delta !== null
    ? `<td style="vertical-align:top;">
<div style="font-size:24px;font-weight:700;color:${deltaColor(delta)};line-height:1;">${formatDelta(delta)}</div>
<div style="font-size:13px;color:${COLORS.muted};margin-top:2px;">vs last week (${prevAvsBrand!.toFixed(1)})</div>
</td>`
    : `<td style="vertical-align:top;"><div style="font-size:13px;color:${COLORS.muted};padding-top:8px;">First run, baseline established</div></td>`
}
</tr></table>

<p style="margin:0 0 10px;font-size:13px;font-weight:600;color:${COLORS.ink};text-transform:uppercase;letter-spacing:0.05em;">Per-engine scores</p>
<table cellpadding="0" cellspacing="0" border="0" width="100%" style="margin:0 0 22px 0;">
${llmRowsHtml}
</table>

<p style="margin:0 0 4px;font-size:13px;font-weight:600;color:${COLORS.ink};text-transform:uppercase;letter-spacing:0.05em;">Top gaps this week</p>
<p style="margin:0 0 10px;font-size:13px;color:${COLORS.muted};">Prompts where ${brandName} was not mentioned</p>
<table cellpadding="0" cellspacing="0" border="0" width="100%" style="margin:0 0 16px 0;">
${gapRowsHtml}
</table>

${proBlurbHtml}

${button(dashboardUrl, "View full report")}
`;

  const preheader = `${brandName} scored ${avsBrand.toFixed(1)}/100 this week${
    delta !== null
      ? ` (${delta >= 0 ? "+" : ""}${delta.toFixed(1)} vs last week)`
      : ""
  }.`;

  const html = wrapEmail(bodyHtml, { preheader, title: subject });

  // ── Plain text fallback ────────────────────────────────────────────────
  const llmTextLines = Object.entries(perLlm)
    .map(([key, score]) => `  ${(LLM_LABELS[key] ?? key).padEnd(14)} ${score.toFixed(1)}/100`)
    .join("\n");

  const gapTextLines =
    gapPrompts.length > 0
      ? gapPrompts
          .map(
            (g, i) =>
              `${i + 1}. "${g.prompt_text}"\n   Missed by: ${
                g.llms_missed.map((k) => LLM_LABELS[k] ?? k).join(", ") || "all LLMs"
              } | Category: ${g.category}`
          )
          .join("\n\n")
      : "No significant gaps this week.";

  const deltaText =
    delta !== null
      ? ` (${formatDelta(delta)} vs last week, previous: ${prevAvsBrand!.toFixed(1)})`
      : " (first run, baseline established)";

  const text = `NeuralReach Weekly AI Visibility Report
${runDateDisplay}

Brand: ${brandName}
AI Visibility Score: ${avsBrand.toFixed(1)}/100${deltaText}

PER-ENGINE SCORES
${llmTextLines}

TOP GAPS THIS WEEK
(Prompts where ${brandName} was not mentioned)

${gapTextLines}
${
  plan === "starter"
    ? `
UPGRADE TO PRO
Get a personalised Fix Report with schema markup, content gaps, and entity authority recommendations.
${appUrl}/pricing

`
    : ""
}
View full report:
${dashboardUrl}

Manage subscription:
${appUrl}/dashboard

NeuralReach, AI Search Visibility for B2B SaaS
Support: ${supportEmail}
`;

  return { subject, html, text };
}
