-- ============================================================
-- NeuralReach — Tracked Brands + Customer Scoring Runs
-- Migration: 0003_tracked_brands
-- Created: 2026-05-28
-- ============================================================

-- Enable uuid extension if not already enabled
create extension if not exists "uuid-ossp";

-- ────────────────────────────────────────────────────────────
-- tracked_brands
-- One row per customer (unique customer_id).
-- Stores brand + up to 3 competitors + optional profile fields
-- used to construct the BrandProfile for the scorer.
-- ────────────────────────────────────────────────────────────
create table if not exists public.tracked_brands (
  id              uuid primary key default uuid_generate_v4(),
  customer_id     uuid not null references public.customers(id) on delete cascade,
  brand_name      text not null,
  brand_url       text not null,
  competitors     jsonb not null default '[]',
    -- [{name: string, url: string}]
  -- Optional BrandProfile fields (filled in from onboarding or defaulted by scorer)
  category        text,   -- e.g. "CRM", "project management tool"
  segment         text,   -- e.g. "B2B SaaS startups"
  use_case_1      text,
  use_case_2      text,
  integration_1   text,
  integration_2   text,
  role_title      text,   -- "role" is a reserved word; stored as role_title
  created_at      timestamptz not null default now(),
  unique (customer_id)    -- one tracked brand per customer for now
);

comment on table public.tracked_brands is
  'Per-customer brand being tracked. Written server-side via API route.';

-- Row Level Security
alter table public.tracked_brands enable row level security;

-- Authenticated users can SELECT their own row (via customer email → customers.id join)
create policy "tracked_brands_own_select" on public.tracked_brands
  for select using (
    customer_id in (
      select id from public.customers
      where email = auth.jwt() ->> 'email'
    )
  );

-- Service role gets full access (server-side writes)
create policy "tracked_brands_service_all" on public.tracked_brands
  for all using (auth.role() = 'service_role');

-- Index for fast customer lookups
create index if not exists tracked_brands_customer_id
  on public.tracked_brands (customer_id);


-- ────────────────────────────────────────────────────────────
-- customer_scoring_runs
-- One row per (customer, date). Stores AVS, per-LLM breakdown,
-- top-3 gap prompts, and optional fix report for Pro tier.
-- ────────────────────────────────────────────────────────────
create table if not exists public.customer_scoring_runs (
  id              uuid primary key default uuid_generate_v4(),
  customer_id     uuid not null references public.customers(id) on delete cascade,
  run_date        date not null,
  avs_brand       numeric not null,
  per_llm         jsonb not null,
    -- {openai: 54.3, anthropic: 49.1, perplexity: 47.0, google: 31.0}
  gap_prompts     jsonb not null,
    -- [{prompt_id, prompt_text, category, llms_missed: [str]}] — top 3
  fix_report_md   text,
    -- Pro only: markdown fix report generated by claude-haiku-4-5
  created_at      timestamptz not null default now(),
  unique (customer_id, run_date)
);

comment on table public.customer_scoring_runs is
  'Per-customer scoring run results. Written by scorer/run_for_customer.py.';

-- Row Level Security
alter table public.customer_scoring_runs enable row level security;

-- Authenticated users can SELECT their own rows
create policy "scoring_runs_own_select" on public.customer_scoring_runs
  for select using (
    customer_id in (
      select id from public.customers
      where email = auth.jwt() ->> 'email'
    )
  );

-- Service role gets full access
create policy "scoring_runs_service_all" on public.customer_scoring_runs
  for all using (auth.role() = 'service_role');

-- Indexes
create index if not exists scoring_runs_customer_id
  on public.customer_scoring_runs (customer_id);

create index if not exists scoring_runs_customer_date
  on public.customer_scoring_runs (customer_id, run_date desc);
